version: '3.9'

services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - product_service

  user_service:
    build:
      context: ./user_service
    ports:
      - "8001:8001"

  product_service:
    build:
      context: ./product_service
    ports:
      - "8002:8002"
